### ISSUE TITLE
feat: module hover tooltip for pnpm catalogs

### ISSUE THREAD

**Issue by mmellado** [tjx666/package-manager-enhancer#19]
PNPM has introduced support for the catalog protocol, which allows us to define dependency versions in `pnpm-workspace.yaml` under the catalog key. Would be great to be able to get dependency version tooltips in this file as well, to make it easier to check catalog dependency versions all at once.

Example:

**pnpm-workspace.yml**
```yaml
packages:
    - 'packages/**/*'

catalog:
    '@types/node': ^20.14.15
    typescript: ^5.5.4
```

PNPM Catalogs description: https://pnpm.io/catalogs
